#!/usr/bin/env bash
# Displays "Best School" 10 times using while loop

index=0

while [ $index -le 20 ]
do
  echo "$index"
  case $index in
	  "4") echo "bad luck from China";;
	  "9") echo "bad luck from Japan";;
	  "17") echo "";
  ((index++))
done
