#!/usr/bin/env bash
# Displays "Best School" 10 times using while loop

i=0

while [ $i -lt 10 ]
do
  ((i++))

  if [[ $i -eq 9 ]]
  then
	  echo "Hi"
  elif [[ $i -ne 9 ]]
  then
	  echo "Best School"
  fi
done
